### PR TITLE
wc_sessionRequest method

### PR DESCRIPTION
**Pull request by dukevantreta**
Adds the `wc_sessionRequest` method documentation.

### CODE REVIEW

**Comment by dukevantreta** [comment]
On google docs, the success acknowledgement response is a common boolean like all other methods. If this is the intended response for this method, we need a response method (`wc_sessionResponse`) to respond with the outcome of the request. For example, an approval or rejection of a transaction.

**Comment by jakubuid** [comment]
> On google docs, the success acknowledgement response is a common boolean like all other methods. If this is the intended response for this method, we need a response method (`wc_sessionResponse`) to respond with the outcome of the request. For example, an approval or rejection of a transaction.

Yea good observation. I believe it's by accident. I vote to keep result for request the response. Imo there is no need for `wc_sessionResponse`.

**Comment by llbartekll** [comment]
`wc_sessionResponse` doesn't make sense 🤣

**Comment by pedrouid** [comment]
The reason you wouldn't need wc_sessionResponse is because the JSON-RPC standard already has binding between a request and a response

This means that a wc_sessionRequest request will always expect a corresponding response with the same JSON-RPC id

**Pull request merged**
